### ISSUE TITLE
[HOTFIX] 심사 리젝 사유 수정

### ISSUE THREAD

**Issue by dayo2n** [Dr-Yomang/Yomang#111]
# Description
심사에서 리젝 당한 부분을 해결합니다

# TODO
- [x] 아이패드 스크린샷찍어서 미리보기 재제출
- [x] 애플로로그인 후 이름을 입력받는 플로우 삭제
- [x] 상대방에게 받은 초대링크를 authViewModel에서 관리하고, 탈퇴할 때 nil로 초기화
- [x] 새로 그린 앱 아이콘으로 변경
- [x] ~~탈퇴할 때 재로그인해서 auth code를 받아야 하는 버그~~ 확인되지 않음. 발생하면 로그아웃 후 탈퇴하면 성공
- [x] 탈퇴하고 다시 돌아왔을 때 LinkView가 다시 뜨지 않음
