### ISSUE TITLE
[FEAT] Setting View Model

### ISSUE THREAD

**Issue by dayo2n** [Dr-Yomang/Yomang#37]
# Description
Setting View에서 처리해야하는 로직을 담은 뷰모델을 생성합니다

# TODO
- [x] 프로필 이미지 변경
- [x] 내 계정 설정: 유저네임 변경
- [ ] 파트너 연결
  - [ ] 연결되어있지 않다면?
  - [ ] 연결되어 있다면?
    - [ ] 연결끊기 (파트너아이디 삭제, 지난 데이터 모두 삭제)
- [x] 알림 설정 (알림이 안들어갈 것으로 생각되는데)
- [ ] 탈퇴 후에 다시 가입하려고 하면 버그 있음 (Auth.auth().currentUser가 지워지지 않는다 ....)
