### ISSUE TITLE
[FIX] ViewModel에서 발생하는 버그를 수정합니다

### ISSUE THREAD

**Issue by dayo2n** [Dr-Yomang/Yomang#43]
# Description
도리스와 계정을 연결해서 뷰모델에서 발생하는 버그를 수정합니다

# TODO
- [x] 요망 업데이트 데이터 처리
  - [ ] 요망 만들기 뷰가 들어와야함 일단은 더미데이터를 저장
- [x] linkView에서 '요망둘러보기' 버튼이 비활성화된 것처럼 보임
- [x] 연결 링크 뭐가 들어와야되지?
- [x] 연결이 완료되면 실시간으로 너의요망 뷰 fetch
- [x] '상대방의 첫 요망을 기다리고 있어요' - 연결되었는데도 뜸
- [x] 리액션 버그
- [x] 달 위치가 탭 뷰마다 바껴야됨
- [x] 이모지가 두 개까지만 저장됨
- [ ] 이미지 데이터가 들어오는 순간 요망뷰간 슬라이드를 이용한 전환이 어려워짐
- [x] 위아래로 넘길 때 보이는 요토의 사이즈가 너무 큽니다 + 이미지 사이즈가 안맞춰지는 버그 수정
- [ ] ~~위에서 아래로 내려서 업데이트 필요할거같은데~~
- [ ] ~~signout이랑 연결끊기 분리~~
- [x] widget이 skeleton 코드로만 보임
- [ ] 탭 페이지 엄청 많이 누르면 탭 인디케이터에 버그있음
- [x] 이미 둘 다 연결없이 로그인한 상태라면, 해당 링크를 클릭했을 때 요망뷰에서 연결되는 로직
- [x] 히스토리뷰 그리드 깨짐  
  <img width="300" src="https://github.com/Dr-Yomang/Yomang/assets/57654681/d00a44b1-1a48-4f19-92d5-e93844003984">
