### ISSUE TITLE
[FEAT] Firebase Dynamic Link 적용

### ISSUE THREAD

**Issue by RubiksCube33** [Dr-Yomang/Yomang#47]
# Description
Firebase에서 제공하는 Dynamic Link를 추가합니다.

# TODO
- [x] 기존 딥링크 제거
- [x] Firebase Dynamic Link로 대체
- [x] Dynamic Link 통해서 매개변수 수신
- [x] 사용자가 초대코드 발송할 수 있게 하기
