### ISSUE TITLE
[FEAT] 필수 패키지 및 모델 추가

### ISSUE THREAD

**Issue by RubiksCube33** [Dr-Yomang/Yomang#5]
# Description
Model과 파이어베이스 패키지를 추가합니다.
패키지 추가 이후에는 info.plist 파일이 없을 시 크래시가 발생할 수 있습니다.
해당 파일이 없는 분들은 저에게 방문해주세요.

# TODO
- [x] 모델 파일 추가
- [x] 파이어베이스 패키지 설치
- [x] 앱 진입점에 파이어베이스 관련 작동코드 추가
