### ISSUE TITLE
[FEAT] YomangView 개선

### ISSUE THREAD

**Issue by OreobrO** [Dr-Yomang/Yomang#50]
# Description
이러이러이런걸 개발할 거예요

# TODO
- [x] 뷰에 버튼 추가하기
- [x] 버튼 누르면 화면 전환하기
- [x] 디자인 변경사항 반영하기
- [x] 버튼에 인터랙션 추가
