### ISSUE TITLE
[FIX] 테스트 중 발견한 버그들을 해결합니다

### ISSUE THREAD

**Issue by dayo2n** [Dr-Yomang/Yomang#64]
# Description
아래 버그를 수정합니다

# TODO
- [x] 마크업뷰에서 업로드누르면 progressview 표시
- [x] 요망뷰의 navigation item 사이즈 확인
- [ ] #62 teamID 환경 변수로 세팅: 팀원 전체가 다시 세팅해야할지도? 일단 hold
- [x] 히스토리를 불러오는데 발생한 오류
- [ ] 요망뷰가 전체적으로 위쪽으로 쏠려있음
- [ ] 모든 기기 테스트
- [ ] 파이어베이스 서버 에러 원인 파악 및 해결
- [ ] 탈퇴 버그: 애플로로그인에서 주는 credential 파기하는 방법이 수동으로만 가능 (설정 - 보안 및 암호 - 애플로로그인 - 요망 삭제)
---
# 오류는 아닌 새 기능 또는 리팩토링
- [x] 히스토리 그리드에 리액션달린거 표시
- [x] 초대링크를 통해 접속하면 파트너 상호연결
