### ISSUE TITLE
[FEAT] 파트너 연결끊기, 너의요망뷰에 파트너 이미지 띄우기, 애플서버에 탈퇴 요청

### ISSUE THREAD

**Issue by dayo2n** [Dr-Yomang/Yomang#70]
# Description
자잘하지만 중요한 나머지 기능들을 구현합니다

# TODO
- [x] 파트너 연결끊기
- [x] 너의요망뷰에 파트너 이미지 띄우기
- [x] 애플 서버에 탈퇴 rest api 보내서 revoke token
- [x] 추가로 알림 메시지 변경 (청유형으로)
